name: SpawnOnJoin
version: 1.1
main: spawnonjoin.spawnonjoin.SpawnOnJoin
api-version: 1.16
authors: [ Kamey ]
description: SpawnOnJoin Plugin to Teleport Players on Join
website: viflcraft.tk
commands:
  setjoinspawn:
    description: Sets the spawn location
    usage: /setjoinspawn
    permission: spawnonjoin.admin
  spawn:
    description: Teleports a player to the spawn
    usage: /spawn
    permission: spawnonjoin.command